### ISSUE TITLE
关于IntermediateResultPartition和下游ExecutionVertex连接关系的问题

### ISSUE THREAD

**Issue by yapxue** [danny0405/flink-source-code-analysis#3]
(1). <Flink执行计划生成>这一章节里,在producer和consumer并发度相等时,一个ExecutionVertex只会连接一个partition
(2). 在<Flink网络栈>这一章节里,partition会分成subpartition,而下游的ExecutionVertex会消费来自多个partition的subpartition,这样就连接多个partition了
(1) 和(2)哪个是正确的呢?

**Comment by danny0405** [comment]
可能我描述的不太清楚， 上游的每个 ExecutionVertex(Task) 都会将数据输出到和下游 ExecutionVertex 相同并发的 subPartition 里，至于下游的每个并发 ExecutionVertex 怎么消费上游 subPartition，就要看不同的调度策略了，比如是否有 hash，上下游并发是否相等.

**Comment by yapxue** [comment]
结合回答又研究了一下,现在明白了.
